name: teska_boilerplate
description: "Flutter Web Boilerplate"
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter  
  
  # Core
  envied: ^1.3.3
  web: ^1.1.1
  get_it: ^9.1.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  equatable: ^2.0.7
  flutter_secure_storage: ^9.2.4
  flutter_bloc: ^9.1.1
  easy_localization: ^3.0.8
  dio: ^5.9.0
  logger: ^2.6.2
  go_router: ^17.1.0
  flutter_gen: ^5.10.0

  # UI
  skeletonizer: ^2.1.1
  responsive_framework: ^1.5.1
  toastification: ^3.0.3

  # Utilities
  collection: ^1.19.1
  device_preview: ^1.3.1
  lottie: ^3.3.2
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.13.0
  very_good_analysis: ^10.0.0
  envied_generator: ^1.3.3
  build_runner: ^2.10.4
  go_router_builder: ^4.2.0
  json_serializable: ^6.11.2
  freezed: ^3.2.3
  rps: ^0.7.0


flutter:
  uses-material-design: true
  assets:
    - assets/localization/
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/lotties/
